name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: test1
      run: echo v1
    - name: test2
      run: |
        mkdir build
        cd build
        cmake ../
        make -j2
        ./test
