name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: test1
      run: echo v1
    - name: test2
      run: |
        mkdir build
        cd build
        cmake ../
        make -j2
        ./test
  root:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: ro
      run: |
        wget "https://root.cern/download/root_v6.18.04.source.tar.gz"
        tar -zxf root_v6.18.04.source.tar.gz
        mkdir build
        cd build
        cmake ../root-6.18.04
        make -j2
        make install

