name: CI

on: [push]

jobs:
  build:
    runs-on: [macos-latest,ubuntu-latest]
    steps:
    - uses: actions/chenxu@v1
    - name: test1
      run: test1
    - name: test2
      run: |
        mkdir build
        cd build
        cmake ../
        make -j2
        ./test
